# Site settings
title:Deepak RB
description: "Learn and build"
baseurl: '/MyBlog' # for test: remove string '/space-jekyll-templa' to ''
url: "http://deepakrajendra.github.io" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https:yourusername.githu.io'
# User settings
username: Deepak RB
user_title: .Net Developer
email: deepakrbabudev@gmail.com
twitter_username: deepakrajendra
github_username:  deepakrajendra
gplus_username:  deepakrbabu
disqus_username: deepak

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
  - title: series
    url: /series
  - title: tags
    url: /tags
  - title: about me
    url: /about
# projects in header index
projects:
  - name: Movie Wiki using Angular2
    url: https://github.com/deepakrajendra/Angular2-MovieWiki
  - name: Weather app using Ionic 2
    url: https://github.com/deepakrajendra/WeatherApp
  - name: Billing system using AngularJS and Web API
    url: https://github.com/deepakrajendra/Billing-System-using-AngularJS
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
